apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    strategy.spinnaker.io/max-version-history: '5'
  name: spinnaker-commits
  namespace: spinnaker
spec:
  replicas: 75
  revisionHistoryLimit: 5
  template:
    metadata:
      labels:
        app: spinnaker-commits
    spec:
      containers:
        - image: >-
            docker.io/justinrlee/spinnaker-commits:${trigger.buildNumber}
          name: spinnaker-commits
          resources:
            limits:
              cpu: 50m
              memory: 16Mi
