apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    strategy.spinnaker.io/max-version-history: '10'
  name: spinnaker-commits
  namespace: spinnaker
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: spinnaker-commits
    spec:
      containers:
        - image: >-
            docker.io/justinrlee/spinnaker-commits:${trigger.buildNumber}
          name: spinnaker-commits
          resources:
            limits:
              cpu: 100m
              memory: 64Mi
