apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/managed-by: spinnaker
    app.kubernetes.io/name: commits
  name: spinnaker-commits-service
  namespace: spinnaker
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: spinnaker-commits
  type: LoadBalancer
